### ISSUE TITLE
Can't find the code

### ISSUE THREAD

**Issue by mboaz17** [IPMI-ICNS-UKE/multiscale#1]
Dear Mr.  Schmitz,

I would like to try out this method, but I couldn't find the actual code here.
Could you please send a link to it?

Many thanks,
Boaz

**Comment by RSchmitzHH** [comment]
I am currently refactoring it, will be uploaded later this day. Many thanks for your interest, and patience,
Rüdiger

**Comment by RSchmitzHH** [comment]
Hi Boaz, 
the sources should now be available in master. Drop me a message in case you have any problems.
Best,
Rüdiger

**Comment by mboaz17** [comment]
What a quick response...
Thanks a lot!

Boaz
