### ISSUE TITLE
question about the results in experimental section

### ISSUE THREAD

**Issue by codeskings** [IPMI-ICNS-UKE/multiscale#4]
Thank you for providing the code for such excellent work.

When I was reading your paper, I understood that the results in the experimental section were based on the subimages sampled randomly from the validation slides in each fold, correct? then these results (particularly the Jaccard index calculation) were not conducted on the level of the entire validation slide?
I just want to confirm that in order to understand how can I compare with your work?

Many thanks

**Comment by RSchmitzHH** [comment]
Hi. Many thanks for your request. Yes, your understanding should be correct, the results are w.r.t. the randomly sampled subimages. Very happy to hear that our paper and code helped you with your work -- please feel free to reach out also via e-mail in case there is anything else I can help you with. (Would be interesting to hear what you are working on based on our paper?) 
Best

**Comment by codeskings** [comment]
Hello. Thanks for the reply. 
I have been working for a while on this topic for my thesis, and honestly, your paper is what introduced me to this field. 
Although the topic is challenging, it is interesting at the same time.
I am working now with unet and attention as my base framework. However, I am facing challenges regarding two WSIs from the validation part of the PAIP dataset, all the predictions of the remaining slides are good but these two are bad :(
Anyway, many thanks again for your interest and help.
